### PR TITLE
Make User and Group Serializable

### LINKED ISSUE #129: Resources should be Serializable
Just played a bit with the osiam docker image.

After a restart of the tomcat server I see some exceptions in the log indicating that scim `User`s or `Resource`s in general cannot be serialized which makes tomcat bark when it tries to serialize HttpSession contents.

I'd suggest that you make `Resource`s serializable to avoid such problems.

```
SEVERE: IOException while loading persisted sessions: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.osiam.resources.scim.User
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.osiam.resources.scim.User
```

### PR DESCRIPTION
**Pull request by sputnik27**
Fixes #129

The classes implement the interface `Serializable` and have a
`serialVersionUID` field.

A test for each of the classes tests that no exception is thrown when
serializing and deserializing the object, and that the deserialized is
equal to the original.

### CODE REVIEW

**Comment by tkrille** [comment]
You have to make all components `@Serializable`, not just `User` and `Group`.

**Comment by tkrille** [comment]
LGTM, but we have to wait until the discussion in #129 is finished.

**Comment by wallner** [comment]
Looks good to me, although I would like to see tests that try to serialize and deserialize at least a little more complicated object graph. I would suggest one where you (de-)serialize a user with an email address and a multivalued attribute?

**Comment by sputnik27** [comment]
@wallner Thanks for your comment. I updated my PR.

File: src/test/groovy/org/osiam/resources/scim/UserSpec.groovy [hunk 1]
```diff
@@ -390,4 +391,25 @@ class UserSpec extends Specification {
                 .setValue('x509Certificat')
                 .build()
     }
+
+    def 'user can be serialized and deserialized'() {
+        given:
+        User user = new User.Builder("UserName")
+                .addEmail(new Email.Builder().setValue('foo@example.com').setType(Email.Type.WORK).build())
+                .addPhoneNumber(new PhoneNumber.Builder().setDisplay("phone").setType(PhoneNumber.Type.FAX).build())
+                .setActive(true).build()
```
Comment (tkrille) [inline src/test/groovy/org/osiam/resources/scim/UserSpec.groovy]: Could you add an extension too, please?

**Comment by sputnik27** [comment]
In case anyone has the time to review this, please do so :)

@tkrille @wallner @dacrome

File: src/main/java/org/osiam/resources/scim/ExtensionFieldType.java [hunk 2]
```diff
@@ -293,4 +303,13 @@ protected void ensureValueIsNotNull(Object value) {
         checkArgument(value != null, "The given value cannot be null.");
     }
 
+    private void writeObject(ObjectOutputStream objectOutputStream) throws IOException {
+        objectOutputStream.defaultWriteObject();
+    }
+
+    private void readObject(ObjectInputStream objectInputStream) throws ClassNotFoundException, IOException {
+        objectInputStream.defaultReadObject();
+
```
Comment (dacrome) [inline src/main/java/org/osiam/resources/scim/ExtensionFieldType.java]: Remove this empty line

File: src/main/java/org/osiam/resources/scim/Meta.java [hunk 3]
```diff
@@ -68,12 +71,12 @@ private Meta(Builder builder) {
 
     /**
      * Gets the URI of the Resource being returned.
-     * 
+     * <p/>
```
Comment (dacrome) [inline src/main/java/org/osiam/resources/scim/Meta.java]: Is the paragraph really necessary?

File: src/main/java/org/osiam/resources/scim/Meta.java [hunk 4]
```diff
@@ -96,12 +99,12 @@ public String getVersion() {
 
     /**
      * Gets the attributes to be deleted from the Resource
-     * 
+     * <p/>
```
Comment (dacrome) [inline src/main/java/org/osiam/resources/scim/Meta.java]: same here

File: src/test/groovy/org/osiam/resources/scim/GroupSpec.groovy [hunk 5]
```diff
@@ -119,4 +119,28 @@ class GroupSpec extends Specification {
...
+        when:
+        def newGroup = (Group) SerializationUtils.deserialize(SerializationUtils.serialize(group))
+
+        then:
+        group == newGroup
+        group.getExternalId() == newGroup.getExternalId()
+        group.getMeta() == newGroup.getMeta()
+        group.getMembers().getAt(0) == newGroup.getMembers().getAt(0)
+    }
+
```
Comment (dacrome) [inline src/test/groovy/org/osiam/resources/scim/GroupSpec.groovy]: Remove this empty line

File: src/test/groovy/org/osiam/resources/scim/UserSpec.groovy [hunk 6]
```diff
@@ -260,7 +263,7 @@ class UserSpec extends Specification {
         def extensions = new HashSet<Extension>()
         extensions.add(EXTENSION_EMPTY)
         def user = new User.Builder('test')
-                //.addExtensions([(EXTENSION_URN): EXTENSION_EMPTY])
+        //.addExtensions([(EXTENSION_URN): EXTENSION_EMPTY])
```
Comment (dacrome) [inline src/test/groovy/org/osiam/resources/scim/UserSpec.groovy]: I know you didn't add this line, but please remove it

File: src/main/java/org/osiam/resources/scim/Meta.java (hunk 3 above)
Comment (sputnik27) [inline src/main/java/org/osiam/resources/scim/Meta.java]: This happened by using the formatter. In general, I can't see any disadvantage of having the tag, except that it looks somewhat ugly in the source. Furthermore, it seems to be [best practice](http://blog.joda.org/2012/11/javadoc-coding-standards.html) to have `<p/>` tags between paragraphs.

**Comment by dacrome** [comment]
Thanks!

**Comment by wallner** [comment]
Please add a `CHANGELOG.md` entry for this.

**Comment by sputnik27** [comment]
> Please add a `CHANGELOG.md` entry for this.

Done. I assume this is a *change*. If anyone disagrees, please tell me.

**Comment by wallner** [comment]
Looks good from my side.

File: src/main/java/org/osiam/resources/scim/MemberRef.java [hunk 7]
```diff
@@ -199,6 +206,8 @@ public MemberRef build() {
      * Represents an Member reference type.
      */
     public static class Type extends MultiValuedAttributeType {
+        private static final long serialVersionUID = 5163337803191562964L;
```
Comment (tkrille) [inline src/main/java/org/osiam/resources/scim/MemberRef.java]: This can be removed, because this sub-class does not define any additional fields.

File: src/main/java/org/osiam/resources/scim/ExtensionFieldType.java [hunk 8]
```diff
@@ -205,13 +211,17 @@ public String toString(Boolean value) {
     };
 
     /**
+     * Since this field can not be serialized, it will be created when the object is de-serialized (see readObject()).
+     */
+    private static transient DateTimeFormatter dateTimeFormatter = ISODateTimeFormat.dateTime().withZoneUTC();
```
Comment (tkrille) [inline src/main/java/org/osiam/resources/scim/ExtensionFieldType.java]: you can remove `@Transient`, static fields are not serialized anyways.

File: src/main/java/org/osiam/resources/scim/ExtensionFieldType.java [hunk 9]
```diff
@@ -293,4 +303,12 @@ protected void ensureValueIsNotNull(Object value) {
...
     }
 
+    private void writeObject(ObjectOutputStream objectOutputStream) throws IOException {
+        objectOutputStream.defaultWriteObject();
+    }
+
+    private void readObject(ObjectInputStream objectInputStream) throws ClassNotFoundException, IOException {
+        objectInputStream.defaultReadObject();
+        dateTimeFormatter = ISODateTimeFormat.dateTime().withZoneUTC();
+    }
```
Comment (tkrille) [inline src/main/java/org/osiam/resources/scim/ExtensionFieldType.java]: These 2 methods can be removed. It's not necessary to create the date formatter each time an instance of this class is deserialized.

**Comment by tkrille** [comment]
Thank you
